### ISSUE TITLE
Non-minified source is missing. It's unclear how it works internally.

### ISSUE THREAD

**Issue by iki** [philipwalton/private-parts#3]

**Comment by philipwalton** [comment]
The non-minified source is here:
https://github.com/philipwalton/private-parts/blob/master/index.js

The private-parts.js file is specifically for the browser and built using browserify. It's just a wrapper around the contents of index.js.

I guess I can see how a non-minified version that works in the browser could be useful for debugging, though the browserify code is somewhat obtuse anyway.

**Comment by philipwalton** [comment]
Fixed via a8dd37bedeb91c06588377786308d9bdabc465a8.
