### ISSUE TITLE
How about privating arrays?

### ISSUE THREAD

**Issue by goowikns** [philipwalton/private-parts#4]
Hi,

I'm still quite a rookie when it comes to OOP in javascript.
But how does this work with arrays? If you return the array aren't you returning the reference?
Which makes it possible to still push/remove elements?

**Comment by philipwalton** [comment]
The technique used by this library actually uses two different objects, not just a reference. One object holds the public data, and one hidden object holds the private data.

In other words, arrays don't present any special challenge, though I don't really know why you'd want private data on an array unless you were using it as an object, in which case just use an object.
