### ISSUE TITLE
Access private properties inside private methods

### ISSUE THREAD

**Issue by beogip** [philipwalton/private-parts#6]
Here is an example of the issue. I'm not sure if i'm doing something wrong or is an issue of the lib.

``` javascript
function FooClass()
{
   _(this).someObject = {
        someValue : 1
    };
}

privateMethods = Object.create(FooClass.prototype);
privateMethods.fooMethod = function()
{
  console.log(_(this).someObject.someValue); // ---> this throws an error, ' Cannot read property 'someValue' of undefined
}
var _ = require('private-parts').createKey(privateMethods);
```

Thanks! excellent work

**Comment by philipwalton** [comment]
Did you ever call the `FooClass` constructor? That's where the `someObject` property is being set, so, based on the error message, it sounds like you're not calling `new FooClass()`.

I also don't see anywhere in your code where you're calling `_(this).fooMethod`. Can you show me the actual code you're running?

**Comment by beogip** [comment]
Sorry, it was a problem in my code. There was a strange loop while conducting an instance. Sorry for creating this issue, I am very embarrassed.

**Comment by philipwalton** [comment]
No worries. I'm glad you figured it out.
