### ISSUE TITLE
Great minds think alike. 

### ISSUE THREAD

**Issue by trusktr** [philipwalton/private-parts#7]
I'm doing a similar thing: [this](https://github.com/infamous/motor/blob/joe/src/nodes/Scene.js#L7-L8) and [this](https://github.com/infamous/motor/blob/joe/src/utilities/Privates.js). Up next I was going to implement that into my [lowclass](https://www.npmjs.com/package/lowclass) library. Then I stumbled on your stuff. :blush:

**Comment by philipwalton** [comment]
Nice!
