### ISSUE TITLE
ES6 - Arrow functions

### ISSUE THREAD

**Issue by ceiger89** [philipwalton/private-parts#8]
Private Parts isn't work with public arrow functions.

``` javascript
var _ = require('private-parts').createKey();

function SomeClass(text) {
    // `privateProperty` is not accessible outside this module
    _(this).privateProperty = text;
}

SomeClass.prototype.getPrivateProperty = function() {
    return _(this).privateProperty;
};

SomeClass.prototype.setPrivateProperty = function(value) {
    return _(this).privateProperty = value;
};

SomeClass.prototype.getPrivateProperty2 = () => {
    return _(this).privateProperty;
};

SomeClass.prototype.setPrivateProperty2 = value => {
    return _(this).privateProperty = value;
};


var a = new SomeClass ('test');
var b = new SomeClass ('test2');

console.warn(a.getPrivateProperty(), b.getPrivateProperty());
console.warn(a.getPrivateProperty2(), b.getPrivateProperty2());
```
## console output

> test test2
> undefined undefined

**Comment by philipwalton** [comment]
In your example, I don't think `this` is what you're expecting it to be when you're using arrow functions.

In the following code:

``` js
SomeClass.prototype.getPrivateProperty2 = () => {
    return _(this).privateProperty;
};
```

The `this` context within the arrow function is getting bound to whatever context `this` is within the definition. In you're case it's either going to be `window` (or `undefined` if you're using `'use strict'`).

This jsbin shows how your problem isn't limited to the private parts library:
http://jsbin.com/yadanaqogu/edit?js,console
