### ISSUE TITLE
Use native bind

### ISSUE THREAD

**Issue by mightyiam** [philipwalton/private-parts#9]
Should be fine by now, right?

**Comment by philipwalton** [comment]
I'm not sure what this is in reference to.

**Comment by mightyiam** [comment]
https://github.com/philipwalton/private-parts/blob/aa90f4a5c22b6e28aeb2158ed16e63700ddf32df/index.js#L48-L59

**Comment by philipwalton** [comment]
Ahh, it's been a while since I touched this library, but the tests run via PhantomJS, and I'm not sure if that's been updated to work with `bind()`.

Happy to accept a PR to modernize it, but I'm probably not going to take the time to investigate myself for such a small change.
